(define (a u v w x)
                    (if (eq? u 0)
                        (b v w x)
                        (a (+ u (- 1)) v w x)))
(define (b q r x)
                    (let ([p (+ q r)])
                      (e (+ q r) p x)))
(define (c x) (+ 5 x))
(define (e n p x)
                    (if (eq? n 0)
                        (c p)
                        (o (+ n (- 1)) p x)))
(define (o n p x)
                    (if (eq? 0 n)
                        (c x)
                        (e (+ n (- 1)) p x)))

(let ([x 5]) (a 3 2 1 x))
