(let ([f (lambda (x) (+ x (- 1)))])
 (let ([g (lambda (x) (+ x (- 1)))])
  (let ([t (lambda (x) (+ x (- 1)))])
   (let ([j (lambda (x) (+ x (- 1)))])
    (let ([i (lambda (x) (+ x (- 1)))])
     (let ([h (lambda (x) (+ x (- 1)))])
      (let ([x 80])
       (let ([a (f x)])
        (let ([b (g x)])
         (let ([c (h (i (j (t x))))])
          (+ a (+ b (+ c 0)))))))))))))
